package langdb

import (
	"archive/zip"
	"bytes"
	"reflect"
	"sort"
	"testing"
)

// jarBytes builds a zip in memory and returns it as a string, so a jar can be
// written into a test tree with the same writeTree helper every other reader's
// tests use -- and so a nested archive is just an entry whose content is
// another call to this.
func jarBytes(t *testing.T, entries map[string]string) string {
	t.Helper()
	names := make([]string, 0, len(entries))
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for _, name := range names {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := w.Write([]byte(entries[name])); err != nil {
			t.Fatal(err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatal(err)
	}
	return buf.String()
}

// log4jJar is the flagship fixture: the shape of a real log4j-core jar, Maven
// coordinates and all.
func log4jJar(t *testing.T, withJndiLookup bool) string {
	t.Helper()
	entries := map[string]string{
		"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\n",
		"META-INF/maven/org.apache.logging.log4j/log4j-core/pom.properties": "" +
			"#Generated by Maven\n" +
			"groupId=org.apache.logging.log4j\n" +
			"artifactId=log4j-core\n" +
			"version=2.14.1\n",
		"org/apache/logging/log4j/core/Logger.class": "\xca\xfe\xba\xbe",
	}
	if withJndiLookup {
		entries["org/apache/logging/log4j/core/lookup/JndiLookup.class"] = "\xca\xfe\xba\xbe"
	}
	return jarBytes(t, entries)
}

func readMaven(t *testing.T, files map[string]string) Result {
	t.Helper()
	fsys := writeTree(t, files)
	roots, err := FindRoots(fsys)
	if err != nil {
		t.Fatal(err)
	}
	res, err := (&Maven{}).Read(fsys, roots[FormatMaven])
	if err != nil {
		t.Fatal(err)
	}
	return res
}

// The tiers exist because a jar frequently does not say what it is. Each one
// has to produce a queryable Maven coordinate, and each has to be honest about
// whether the build wrote it or this reader guessed it.
func TestCoordinateTiers(t *testing.T) {
	files := map[string]string{
		// Tier 1: Maven wrote the coordinates.
		"/opt/lib/log4j-core-2.14.1.jar": log4jJar(t, true),

		// Tier 2: Gradle wrote no META-INF/maven, but Spring ships GraalVM
		// reachability metadata filed under the same two coordinates.
		"/opt/lib/spring-core-6.1.14.jar": jarBytes(t, map[string]string{
			"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\n" +
				"Implementation-Version: 6.1.14\r\n",
			"META-INF/native-image/org.springframework/spring-core/native-image.properties": "",
			"org/springframework/core/Ordered.class":                                        "",
		}),

		// Tier 3: nothing but a manifest, and its vendor id is a free-text
		// string that happens to look like a groupId.
		"/opt/lib/thing.jar": jarBytes(t, map[string]string{
			"META-INF/MANIFEST.MF": "Manifest-Version: 1.0\r\n" +
				"Implementation-Vendor-Id: com.example\r\n" +
				"Implementation-Title: thing\r\n" +
				"Implementation-Version: 3.2.1\r\n",
			"com/example/thing/Main.class": "",
		}),

		// Tier 4: a conventional file name and the classes' own package prefix.
		"/opt/lib/widget-1.0.0.jar": jarBytes(t, map[string]string{
			"net/corp/widget/Widget.class": "",
			"net/corp/widget/Helper.class": "",
		}),
	}

	res := readMaven(t, files)
	if len(res.Unreadable) != 0 || len(res.Unidentified) != 0 {
		t.Fatalf("unreadable=%v unidentified=%v", res.Unreadable, res.Unidentified)
	}

	type coord struct {
		name, version string
		known         bool
	}
	got := map[string]coord{}
	for _, p := range res.Packages {
		got[p.Dir] = coord{p.Name, p.Version, p.CoordsKnown}
	}
	want := map[string]coord{
		"/opt/lib/log4j-core-2.14.1.jar":  {"org.apache.logging.log4j:log4j-core", "2.14.1", true},
		"/opt/lib/spring-core-6.1.14.jar": {"org.springframework:spring-core", "6.1.14", true},
		"/opt/lib/thing.jar":              {"com.example:thing", "3.2.1", false},
		"/opt/lib/widget-1.0.0.jar":       {"net.corp.widget:widget", "1.0.0", false},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("coordinates =\n%v\nwant\n%v", got, want)
	}
}

// The weakest tier is demonstrably fallible -- guava's classes live under
// com.google.common while its groupId is com.google.guava -- so it offers every
// plausible prefix. One extra name costs one entry in a batch query; missing the
// right one reports a vulnerable artifact as clean.
func TestFilenameTierOffersEveryGroupCandidate(t *testing.T) {
	res := readMaven(t, map[string]string{
		"/opt/lib/guava-32.1.3-jre.jar": jarBytes(t, map[string]string{
			"com/google/common/collect/Lists.class": "",
			"com/google/common/base/Joiner.class":   "",
		}),
	})
	if len(res.Packages) != 1 {
		t.Fatalf("got %d packages, want 1", len(res.Packages))
	}
	p := res.Packages[0]
	if p.Version != "32.1.3-jre" {
		// The split is the last hyphen followed by a digit, which is what keeps
		// the -jre classifier attached rather than mistaken for the artifact.
		t.Errorf("version = %q, want 32.1.3-jre", p.Version)
	}
	// Only the prefix every class shares is used, so collect/ and base/ cancel
	// out -- and com.google:guava, the real coordinate, is among the candidates
	// even though no class lives directly under it.
	want := []string{"com.google.common:guava", "com.google:guava"}
	if got := p.OSVNames(); !reflect.DeepEqual(got, want) {
		t.Errorf("OSVNames() = %v, want %v", got, want)
	}
}

// A Spring Boot image whose inventory is one component has missed the hundred
// jars that are its actual attack surface.
func TestNestedArchivesAreTheirOwnComponents(t *testing.T) {
	res := readMaven(t, map[string]string{
		"/app/app.jar": jarBytes(t, map[string]string{
			"META-INF/maven/com.example/app/pom.properties": "groupId=com.example\nartifactId=app\nversion=1.0\n",
			"BOOT-INF/classes/com/example/app/Main.class":   "",
			"BOOT-INF/lib/log4j-core-2.14.1.jar":            log4jJar(t, true),
			// Not in a specified lib directory, so not a dependency: a fixture
			// no classloader opens must not inventory as a component.
			"BOOT-INF/classes/testdata/sample.jar": jarBytes(t, map[string]string{"a/B.class": ""}),
		}),
	})

	var got []string
	for _, p := range res.Packages {
		got = append(got, p.Name+" @ "+p.Dir)
	}
	want := []string{
		"com.example:app @ /app/app.jar",
		"org.apache.logging.log4j:log4j-core @ /app/app.jar!/BOOT-INF/lib/log4j-core-2.14.1.jar",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("packages =\n%v\nwant\n%v", got, want)
	}
}

// The whole point of the ecosystem: deleting the class is the documented
// Log4Shell mitigation, and the version stays 2.14.1 afterwards. A reader that
// cannot see the difference cannot support the only conclusion here that a
// version-matching scanner gets wrong.
func TestClassListSeesTheLog4ShellMitigation(t *testing.T) {
	const jndi = "org/apache/logging/log4j/core/lookup/JndiLookup.class"

	for _, tc := range []struct {
		name string
		want bool
	}{{"vulnerable", true}, {"patched-by-deletion", false}} {
		t.Run(tc.name, func(t *testing.T) {
			res := readMaven(t, map[string]string{
				"/opt/lib/log4j-core-2.14.1.jar": log4jJar(t, tc.want),
			})
			if len(res.Packages) != 1 {
				t.Fatalf("got %d packages, want 1", len(res.Packages))
			}
			p := res.Packages[0]
			if !p.FilesKnown {
				t.Error("FilesKnown = false; a zip central directory is a manifest")
			}
			var found bool
			for _, f := range p.Files {
				if f == jndi {
					found = true
				}
			}
			if found != tc.want {
				t.Errorf("JndiLookup present = %v, want %v", found, tc.want)
			}
			if p.Version != "2.14.1" {
				t.Errorf("version = %q, want 2.14.1 either way", p.Version)
			}
		})
	}
}

// Multi-release classes are real: a new enough JVM loads them in preference to
// the base copy, so a reader that skipped them would report a class absent that
// the runtime does load.
func TestMultiReleaseClassesCount(t *testing.T) {
	res := readMaven(t, map[string]string{
		"/opt/lib/mr-1.0.jar": jarBytes(t, map[string]string{
			"META-INF/MANIFEST.MF":                           "Multi-Release: true\r\n",
			"org/example/mr/Base.class":                      "",
			"META-INF/versions/17/org/example/mr/Base.class": "",
		}),
	})
	if len(res.Packages) != 1 {
		t.Fatalf("got %d packages, want 1", len(res.Packages))
	}
	p := res.Packages[0]
	// The versioned copy did not invent a second package root; the reader
	// strips META-INF/versions/N before reading the class's own package.
	if want := []string{"org.example"}; !reflect.DeepEqual(p.ImportNames, want) {
		t.Errorf("ImportNames = %v, want %v", p.ImportNames, want)
	}
	if p.Name != "org.example.mr:mr" {
		t.Errorf("name = %q, want org.example.mr:mr", p.Name)
	}
}

// An archive nobody can name and an archive nobody can open are the same
// failure: something is installed and this scan cannot say what. Neither may be
// silent, because either one blocks a later claim that a component is absent.
func TestUnnameableAndUnreadableArchivesAreReported(t *testing.T) {
	res := readMaven(t, map[string]string{
		// Opens fine, declares nothing, and has no version in its name.
		"/opt/lib/plugin.jar": jarBytes(t, map[string]string{
			"org/example/plugin/Main.class": "",
		}),
		// Ends in .jar and is not a zip. Images carry truncated downloads and
		// jars that are really shell scripts with an archive appended.
		"/opt/lib/broken.jar": "not a zip at all",
	})

	if want := []string{"/opt/lib/plugin.jar"}; !reflect.DeepEqual(res.Unidentified, want) {
		t.Errorf("Unidentified = %v, want %v", res.Unidentified, want)
	}
	if want := []string{"/opt/lib/broken.jar"}; !reflect.DeepEqual(res.Unreadable, want) {
		t.Errorf("Unreadable = %v, want %v", res.Unreadable, want)
	}
	if len(res.Packages) != 0 {
		t.Errorf("packages = %v, want none", res.Packages)
	}
}

// A jar of sources or javadoc ships no executable code at all, which is a
// not_present conclusion the plugin can reach without any advisory detail.
func TestArchiveWithNoClasses(t *testing.T) {
	res := readMaven(t, map[string]string{
		"/opt/lib/thing-1.0-sources.jar": jarBytes(t, map[string]string{
			"META-INF/maven/com.example/thing/pom.properties": "groupId=com.example\nartifactId=thing\nversion=1.0\n",
			"com/example/thing/Main.java":                     "package com.example.thing;",
		}),
	})
	if len(res.Packages) != 1 {
		t.Fatalf("got %d packages, want 1", len(res.Packages))
	}
	p := res.Packages[0]
	if len(p.ImportNames) != 0 || p.ImportNamesKnown {
		t.Errorf("ImportNames = %v (known=%v), want none and not known", p.ImportNames, p.ImportNamesKnown)
	}
	if !p.FilesKnown || len(p.Files) != 2 {
		t.Errorf("Files = %v (known=%v), want both entries listed", p.Files, p.FilesKnown)
	}
}

// maven-shade-plugin merges the metadata of everything it absorbs, so an
// uber-jar honestly declares all of its constituents. Each is a component, and
// a CVE against any of them has to land.
func TestShadedJarDeclaresEveryConstituent(t *testing.T) {
	res := readMaven(t, map[string]string{
		"/opt/lib/uber.jar": jarBytes(t, map[string]string{
			"META-INF/maven/com.example/uber/pom.properties":                "groupId=com.example\nartifactId=uber\nversion=1.0\n",
			"META-INF/maven/com.google.guava/guava/pom.properties":          "groupId=com.google.guava\nartifactId=guava\nversion=31.0\n",
			"com/example/uber/Main.class":                                   "",
			"com/example/uber/shaded/com/google/common/collect/Lists.class": "",
		}),
	})

	var got []string
	for _, p := range res.Packages {
		got = append(got, p.Name+"@"+p.Version)
		if !p.CoordsKnown {
			t.Errorf("%s: CoordsKnown = false, want true", p.Name)
		}
		// Every declared artifact is credited with every entry. There is no way
		// to tell whose class is whose after shading, and the only thing this
		// list is ever used to prove is that something is *not* in it.
		if len(p.Files) != 4 {
			t.Errorf("%s: %d files, want all 4", p.Name, len(p.Files))
		}
	}
	want := []string{"com.example:uber@1.0", "com.google.guava:guava@31.0"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("packages = %v, want %v", got, want)
	}
}

// MANIFEST.MF folds at 72 bytes, and a continuation line begins with exactly
// one space that is not part of the value. Reading it line by line without
// unfolding yields a truncated coordinate.
func TestManifestUnfoldsContinuationLines(t *testing.T) {
	mf := parseManifest("Manifest-Version: 1.0\r\n" +
		"Implementation-Vendor-Id: org.apache.commo\r\n" +
		" ns\r\n" +
		"Implementation-Title: commons-lang3\r\n" +
		"Implementation-Version: 3.12.0\r\n")

	if got := mf["Implementation-Vendor-Id"]; got != "org.apache.commons" {
		t.Errorf("vendor id = %q, want org.apache.commons", got)
	}
	if got := mf["Implementation-Title"]; got != "commons-lang3" {
		t.Errorf("title = %q, want commons-lang3", got)
	}
}

func TestSplitArchiveName(t *testing.T) {
	for _, tc := range []struct{ in, artifact, version string }{
		{"/opt/log4j-core-2.14.1.jar", "log4j-core", "2.14.1"},
		{"guava-32.1.3-jre.jar", "guava", "32.1.3-jre"},
		{"spring-core-6.1.14.JAR", "spring-core", "6.1.14"},
		{"app.jar!/WEB-INF/lib/jackson-databind-2.15.3.jar", "jackson-databind", "2.15.3"},
		{"plugin.jar", "", ""},
		{"jenkins.war", "", ""},
	} {
		artifact, version := splitArchiveName(tc.in)
		if artifact != tc.artifact || version != tc.version {
			t.Errorf("splitArchiveName(%q) = %q, %q; want %q, %q",
				tc.in, artifact, version, tc.artifact, tc.version)
		}
	}
}

// A jar whose classes span two unrelated roots has been repackaged, and nothing
// about its layout implies a coordinate. Guessing one anyway would be the worst
// kind of wrong: a confident name for something else entirely.
func TestGroupCandidatesRefuseUnrelatedRoots(t *testing.T) {
	if got := groupCandidates([]string{"org/foo/A.class", "com/bar/B.class"}); got != nil {
		t.Errorf("groupCandidates = %v, want nil", got)
	}
	if got := groupCandidates([]string{"A.class"}); got != nil {
		t.Errorf("default-package class: groupCandidates = %v, want nil", got)
	}
}

func TestFindRootsFindsArchivesAnywhere(t *testing.T) {
	fsys := writeTree(t, map[string]string{
		"/usr/local/tomcat/lib/catalina.jar": "",
		"/usr/share/java/thing.JAR":          "",
		"/app/app.war":                       "",
		"/opt/enterprise/thing.ear":          "",
		"/app/notes.txt":                     "",
		"/app/jar":                           "",
	})

	roots, err := FindRoots(fsys)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		"/app/app.war",
		"/opt/enterprise/thing.ear",
		"/usr/local/tomcat/lib/catalina.jar",
		"/usr/share/java/thing.JAR",
	}
	if !reflect.DeepEqual(roots[FormatMaven], want) {
		t.Errorf("maven roots = %v, want %v", roots[FormatMaven], want)
	}
}
